In [6]:
import pandas as pd
from datetime import datetime

In [7]:
def Merge_Commodtites(name):
    
    Trade_df = pd.read_excel(f'../Data/New_Work(Revisit_Model)/trade_data/{name}_TradeData_21-22.xlsx')
    # Merge 'year' and 'month' columns and create a new 'date' column
    Trade_df['Date'] = pd.to_datetime(Trade_df[['Year', 'Month']].assign(day=1))
    Trade_df.drop(columns=['Year', 'Month'], inplace=True)
    Trade_df = Trade_df.iloc[:,1:]
#     print(Trade_df.shape)
#     FAO_df = pd.read_excel(f'../Data/New_Work(Revisit_Model)/FAO-Production-Yield-Area harvested.xls',sheet_name=f'{name}')
#     FAO_df.rename(columns={'Year': 'Date'}, inplace=True)
#     print(FAO_df.shape)
    Price_df = pd.read_excel(f'../Data/New_Work(Revisit_Model)/prices2020-2023.xlsx',sheet_name=f'{name}')
#     print(Price_df.tail())
#     print(Price_df.shape)
    Prod_df = pd.read_csv(f'../Data/New_Work(Revisit_Model)/Prod_data/Prod_{name}.csv')
    Prod_df.rename(columns={'Year': 'Date'}, inplace=True)
    Prod_df.drop(columns=['Imports (t)','Exports (t)','Exports per capita (kg)','exports__tonnes__per_capita',
                         'Imports per capita (kg)','imports__tonnes__per_capita','Date'],inplace=True, errors='ignore')
    Prod_df = Prod_df.add_prefix('Prod ')
#     Prod_df.columns = [col.replace('(t)','Kg') for col in Prod_df.columns]
    Prod_df['Date'] = pd.date_range(start=datetime(2010, 1, 1), periods=Prod_df.shape[0], freq=pd.DateOffset(years=1))

    Data_m = pd.DataFrame()
    Data_m['Date'] = pd.date_range(start='01/01/2010', end='01/07/2023', freq='MS')
    
    #Political and Social
    Political_df = pd.read_excel(f'../Data/New_Work(Revisit_Model)/Political/Political_and_social_volatilities-EU_2013_2022.xlsx',sheet_name='Indicators')
    
    #Read Financial Data
    Finicial = pd.read_excel(f'../Data/New_Work(Revisit_Model)/Financial_Data/CPI-GDP-2013-2023.xlsx')
    
    # Merge all DataFrames on the 'Date' column
    merged_df = Prod_df.merge(Data_m, on='Date', how='outer')\
                .merge(Political_df , on='Date', how='outer')\
                .merge(Trade_df, on='Date', how='outer')\
                .merge(Price_df , on='Date', how='outer') #                 .merge(FAO_df, on='Date', how='outer')\
    merged_df.sort_values(by='Date',inplace=True)
#     merged_df.ffill(axis = 0,inplace=True)
    merged_df['Year'] = merged_df['Date'].dt.year
    merged_df['Month'] = merged_df['Date'].dt.month
    merged_df = merged_df.merge(Finicial , on=['Year','Month'], how='outer')
    merged_df.to_excel(f'../Data/New_Work(Revisit_Model)/Final_Data/{name}_Data_10_23.xlsx')
    
    return  merged_df

## Trade Data 

- Meat Fr - F
- Dates
- Egg
- Chicken Fr-F
- Marrow
- Milk

## FAO
- chicken
- Meat
- Dates 
- Lemon 
- Cucumber
- Milk
- Egg

## Prices
- Chicken
- Meat beef
- Spinach
- Marrow
- Cucumber
- Egg_Medium
- Milk 
- Dates

## Prod
- Beef Meat
- Chicken Meat
- Dates
- Eggs
- Milk

## Political

- Food_Availability	
- Food_Security	
- Poverty_&_Development	
- Human_Develpment_Index	
- Pneumococcal	
- Lack_of_Coping_Capacity_Index	
- Vulnerability_Index

## Dates

In [8]:
Dates = Merge_Commodtites('Dates')
Dates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163 entries, 0 to 162
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Prod Population                            14 non-null     float64
 1   Prod Production (t)                        12 non-null     float64
 2   Prod Yield (t/ha)                          12 non-null     float64
 3   Prod Land Use (ha)                         12 non-null     float64
 4   Prod Domestic supply (t)                   11 non-null     float64
 5   Prod Food (t)                              11 non-null     float64
 6   Prod Supply chain waste (t)                11 non-null     float64
 7   Prod Food supply (kg per capita per year)  11 non-null     float64
 8   Prod World Production(t)                   11 non-null     float64
 9   Prod GDP per capita                        11 non-null     float64
 10  Prod GNI per capita                        11 non-null     float64
 11  Prod Inflation rate %                      14 non-null     float64
 12  Date                                       163 non-null    datetime64[ns]
 13  Food Availability                          10 non-null     float64
 14  Food Security                              10 non-null     float64
 15  Poverty & Development                      10 non-null     float64
 16  Human Develpment Index                     10 non-null     float64
 17  Pneumococcal                               10 non-null     float64
 18  Lack of Coping Capacity Index              10 non-null     float64
 19  Vulnerability Index                        10 non-null     float64
 20  Imports Weight (KG)                        24 non-null     float64
 21  Imports Value (AED)                        24 non-null     float64
 22  Non-oil Exports Weight (KG)                24 non-null     float64
 23  Non-oil Exports Value (AED)                24 non-null     float64
 24  Re-exports Weight (KG)                     24 non-null     float64
 25  Re-exports Value (AED)                     24 non-null     float64
 26  Price/Kg(Exp)                              24 non-null     float64
 27  Dates_price                                54 non-null     float64
 28  Year                                       163 non-null    int64
 29  Month                                      163 non-null    int64
 30  CPI_ANNCHG                                 127 non-null    float64
 31  CPI_MTHCHG                                 127 non-null    float64
 32  Oil_price_high                             127 non-null    float64
 33  fertilizer_index                           127 non-null    float64
 34  GDP                                        127 non-null    float64
dtypes: datetime64[ns](1), float64(32), int64(2)
memory usage: 45.8 KB

In [9]:
Dates

,Prod Population,Prod Production (t),Prod Yield (t/ha),Prod Land Use (ha),Prod Domestic supply (t),Prod Food (t),Prod Supply chain waste (t),Prod Food supply (kg per capita per year),Prod World Production(t),Prod GDP per capita,...,Re-exports Value (AED),Price/Kg(Exp),Dates_price,Year,Month,CPI_ANNCHG,CPI_MTHCHG,Oil_price_high,fertilizer_index,GDP
0,8481775.0,825300.0,4.1809,197400.0,801000.0,128000.0,43000.0,15.120639,34157596.9,34165.91331,...,NaN,NaN,NaN,2010,1,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2010,2,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2010,3,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2010,4,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2010,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.650,2023,3,0.182654,-0.058124,80.94000,348.520000,1763526.88
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.650,2023,4,0.531444,-0.068240,83.53000,335.472000,1763526.88
160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.875,2023,5,0.894775,-0.068549,76.69000,331.519361,1763526.88
161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.950,2023,6,1.408778,-0.057505,79.38375,314.761811,1763526.88
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2023,7,1.807864,-0.043091,82.07750,298.004261,1763526.88

## Eggs_Table

In [10]:
Eggs_Table = Merge_Commodtites('Eggs_Table')
Eggs_Table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163 entries, 0 to 162
Data columns (total 43 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Prod Population                                  14 non-null     float64
 1   Prod Production (t)                              12 non-null     float64
 2   Prod production__tonnes__per_capita              12 non-null     float64
 3   Prod Production per capita (kg)                  12 non-null     float64
 4   Prod Yield (kg/animal)                           12 non-null     float64
 5   Prod Domestic supply (t)                         11 non-null     float64
 6   Prod domestic_supply__tonnes__per_capita         11 non-null     float64
 7   Prod Domestic supply per capita (kg)             11 non-null     float64
 8   Prod Food (t)                                    11 non-null     float64
 9   Prod food__tonnes__per_capita                    11 non-null     float64
 10  Prod Food per capita (kg)                        11 non-null     float64
 11  Prod Supply chain waste (t)                      11 non-null     float64
 12  Prod waste_in_supply_chain__tonnes__per_capita   11 non-null     float64
 13  Prod Supply chain waste per capita (kg)          11 non-null     float64
 14  Prod Food supply (kg per capita per year)        11 non-null     float64
 15  Prod Food supply (g per capita per day)          11 non-null     float64
 16  Prod Food supply (kcal per capita per day)       11 non-null     float64
 17  Prod Food supply (Protein g per capita per day)  11 non-null     float64
 18  Prod Food supply (Fat g per capita per day)      11 non-null     float64
 19  Prod Inflation rate %                            14 non-null     float64
 20  Date                                             163 non-null    datetime64[ns]
 21  Food Availability                                10 non-null     float64
 22  Food Security                                    10 non-null     float64
 23  Poverty & Development                            10 non-null     float64
 24  Human Develpment Index                           10 non-null     float64
 25  Pneumococcal                                     10 non-null     float64
 26  Lack of Coping Capacity Index                    10 non-null     float64
 27  Vulnerability Index                              10 non-null     float64
 28  Imports Weight (KG)                              24 non-null     float64
 29  Imports Value (AED)                              24 non-null     float64
 30  Non-oil Exports Weight (KG)                      24 non-null     float64
 31  Non-oil Exports Value (AED)                      24 non-null     float64
 32  Re-exports Weight (KG)                           24 non-null     float64
 33  Re-exports Value (AED)                           24 non-null     float64
 34  Price/Kg(Exp)                                    24 non-null     float64
 35  Local_eggs(30 eggs)                              54 non-null     float64
 36  Year                                             163 non-null    int64
 37  Month                                            163 non-null    int64
 38  CPI_ANNCHG                                       127 non-null    float64
 39  CPI_MTHCHG                                       127 non-null    float64
 40  Oil_price_high                                   127 non-null    float64
 41  fertilizer_index                                 127 non-null    float64
 42  GDP                                              127 non-null    float64
dtypes: datetime64[ns](1), float64(40), int64(2)
memory usage: 56.0 KB

## Meat_beef

In [11]:
Meat_beef = Merge_Commodtites('Meat_beef')
Meat_beef.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163 entries, 0 to 162
Data columns (total 43 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Prod Population                                  14 non-null     float64
 1   Prod Production(t)                               7 non-null      float64
 2   Prod Producing Animals/Slaughtered(Head)         7 non-null      float64
 3   Prod Domestic supply (t)                         11 non-null     float64
 4   Prod domestic_supply__tonnes__per_capita         11 non-null     float64
 5   Prod Domestic supply per capita (kg)             11 non-null     float64
 6   Prod Food (t)                                    11 non-null     float64
 7   Prod food__tonnes__per_capita                    11 non-null     float64
 8   Prod Food per capita (kg)                        11 non-null     float64
 9   Prod Supply chain waste (t)                      11 non-null     float64
 10  Prod waste_in_supply_chain__tonnes__per_capita   11 non-null     float64
 11  Prod Supply chain waste per capita (kg)          11 non-null     float64
 12  Prod Food supply (kg per capita per year)        11 non-null     float64
 13  Prod Food supply (g per capita per day)          11 non-null     float64
 14  Prod Food supply (kcal per capita per day)       11 non-null     float64
 15  Prod Food supply (Protein g per capita per day)  11 non-null     float64
 16  Prod Food supply (Fat g per capita per day)      11 non-null     float64
 17  Prod Inflation rate %                            14 non-null     float64
 18  Date                                             163 non-null    datetime64[ns]
 19  Food Availability                                10 non-null     float64
 20  Food Security                                    10 non-null     float64
 21  Poverty & Development                            10 non-null     float64
 22  Human Develpment Index                           10 non-null     float64
 23  Pneumococcal                                     10 non-null     float64
 24  Lack of Coping Capacity Index                    10 non-null     float64
 25  Vulnerability Index                              10 non-null     float64
 26  Imports Weight (KG)                              24 non-null     float64
 27  Imports Value (AED)                              24 non-null     float64
 28  Non-oil Exports Weight (KG)                      24 non-null     float64
 29  Non-oil Exports Value (AED)                      24 non-null     float64
 30  Re-exports Weight (KG)                           24 non-null     float64
 31  Re-exports Value (AED)                           24 non-null     float64
 32  Price/Kg(Exp)                                    24 non-null     float64
 33  Fresh_Beef_Bone                                  48 non-null     float64
 34  Fresh_Beef_Boneless                              48 non-null     float64
 35  Frozen_Beef                                      43 non-null     float64
 36  Year                                             163 non-null    int64
 37  Month                                            163 non-null    int64
 38  CPI_ANNCHG                                       127 non-null    float64
 39  CPI_MTHCHG                                       127 non-null    float64
 40  Oil_price_high                                   127 non-null    float64
 41  fertilizer_index                                 127 non-null    float64
 42  GDP                                              127 non-null    float64
dtypes: datetime64[ns](1), float64(40), int64(2)
memory usage: 56.0 KB

## Meat_chicken

In [12]:
Meat_chicken = Merge_Commodtites('Meat_chicken')
Meat_chicken.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163 entries, 0 to 162
Data columns (total 33 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Prod Population                                   14 non-null     float64
 1   Prod Stocks(Value)                                7 non-null      float64
 2   Prod Production (t)                               12 non-null     float64
 3   Prod production__tonnes__per_capita               12 non-null     float64
 4   Prod Production per capita (kg)                   12 non-null     float64
 5   Prod Yield (kg/animal)                            12 non-null     float64
 6   Prod Producing or slaughtered animals             12 non-null     float64
 7   Prod Producing or slaughtered animals per capita  12 non-null     float64
 8   Prod Inflation rate %                             14 non-null     float64
 9   Date                                              163 non-null    datetime64[ns]
 10  Food Availability                                 10 non-null     float64
 11  Food Security                                     10 non-null     float64
 12  Poverty & Development                             10 non-null     float64
 13  Human Develpment Index                            10 non-null     float64
 14  Pneumococcal                                      10 non-null     float64
 15  Lack of Coping Capacity Index                     10 non-null     float64
 16  Vulnerability Index                               10 non-null     float64
 17  Imports Weight (KG)                               24 non-null     float64
 18  Imports Value (AED)                               24 non-null     float64
 19  Non-oil Exports Weight (KG)                       24 non-null     float64
 20  Non-oil Exports Value (AED)                       24 non-null     float64
 21  Re-exports Weight (KG)                            24 non-null     float64
 22  Re-exports Value (AED)                            24 non-null     float64
 23  Price/Kg(Exp)                                     24 non-null     float64
 24  Fresh_chicken                                     54 non-null     float64
 25  Frozen_chicken                                    43 non-null     float64
 26  Year                                              163 non-null    int64
 27  Month                                             163 non-null    int64
 28  CPI_ANNCHG                                        127 non-null    float64
 29  CPI_MTHCHG                                        127 non-null    float64
 30  Oil_price_high                                    127 non-null    float64
 31  fertilizer_index                                  127 non-null    float64
 32  GDP                                               127 non-null    float64
dtypes: datetime64[ns](1), float64(30), int64(2)
memory usage: 43.3 KB

## Milk

In [13]:
Milk = Merge_Commodtites('Milk')
Milk.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 163 entries, 0 to 162
Data columns (total 47 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Prod Population                                  14 non-null     float64
 1   Prod Production (t)                              12 non-null     float64
 2   Prod production__tonnes__per_capita              12 non-null     float64
 3   Prod Production per capita (kg)                  12 non-null     float64
 4   Prod Yield (kg/animal)                           12 non-null     float64
 5   Prod Domestic supply (t)                         11 non-null     float64
 6   Prod domestic_supply__tonnes__per_capita         11 non-null     float64
 7   Prod Domestic supply per capita (kg)             11 non-null     float64
 8   Prod Food (t)                                    11 non-null     float64
 9   Prod food__tonnes__per_capita                    11 non-null     float64
 10  Prod Food per capita (kg)                        11 non-null     float64
 11  Prod Animal feed (t)                             11 non-null     float64
 12  Prod feed__tonnes__per_capita                    11 non-null     float64
 13  Prod Animal feed per capita (kg)                 11 non-null     float64
 14  Prod Supply chain waste (t)                      11 non-null     float64
 15  Prod waste_in_supply_chain__tonnes__per_capita   11 non-null     float64
 16  Prod Supply chain waste per capita (kg)          11 non-null     float64
 17  Prod Food supply (kg per capita per year)        11 non-null     float64
 18  Prod Food supply (g per capita per day)          11 non-null     float64
 19  Prod Food supply (kcal per capita per day)       11 non-null     float64
 20  Prod Food supply (Protein g per capita per day)  11 non-null     float64
 21  Prod Food supply (Fat g per capita per day)      11 non-null     float64
 22  Prod Inflation rate %                            14 non-null     float64
 23  Date                                             163 non-null    datetime64[ns]
 24  Food Availability                                10 non-null     float64
 25  Food Security                                    10 non-null     float64
 26  Poverty & Development                            10 non-null     float64
 27  Human Develpment Index                           10 non-null     float64
 28  Pneumococcal                                     10 non-null     float64
 29  Lack of Coping Capacity Index                    10 non-null     float64
 30  Vulnerability Index                              10 non-null     float64
 31  Imports Weight (KG)                              24 non-null     float64
 32  Imports Value (AED)                              24 non-null     float64
 33  Non-oil Exports Weight (KG)                      24 non-null     float64
 34  Non-oil Exports Value (AED)                      24 non-null     float64
 35  Re-exports Weight (KG)                           24 non-null     float64
 36  Re-exports Value (AED)                           24 non-null     float64
 37  Price/Kg(Exp)                                    24 non-null     float64
 38  canned_liquid_milk                               54 non-null     float64
 39  Fresh_milk                                       54 non-null     float64
 40  Year                                             163 non-null    int64
 41  Month                                            163 non-null    int64
 42  CPI_ANNCHG                                       127 non-null    float64
 43  CPI_MTHCHG                                       127 non-null    float64
 44  Oil_price_high                                   127 non-null    float64
 45  fertilizer_index                                 127 non-null    float64
 46  GDP                                              127 non-null    float64
dtypes: datetime64[ns](1), float64(44), int64(2)
memory usage: 61.1 KB